<style>
#nette-debug .nette-composerUpdatesTab .not-installed,
#nette-debug .nette-composerUpdatesTab .no-update,
#nette-debug .nette-composerUpdatesTab .incompatible-update,
#nette-debug .nette-composerUpdatesTab .compatible-update {
	display: inline-block;
	width: 16px;
	height: 16px;
	margin-top: 3px;
	margin-bottom: -4px;
	border-radius: 8px;
}
#nette-debug .nette-composerUpdatesTab .not-installed {
	background: #B1B1B1;
}
#nette-debug .nette-composerUpdatesTab .no-update {
	background: #599B4A;
}
#nette-debug .nette-composerUpdatesTab .incompatible-update {
	background: #FFC029;
}
#nette-debug .nette-composerUpdatesTab .compatible-update {
	background: #E60000;
}
</style>

<?php
$classes = array(
	\ComposerUpdates\PackageInfo::STATUS_NOT_INSTALLED => 'not-installed',
	\ComposerUpdates\PackageInfo::STATUS_NO_UPDATE => 'no-update',
	\ComposerUpdates\PackageInfo::STATUS_INCOMPATIBLE_UPDATE => 'incompatible-update',
	\ComposerUpdates\PackageInfo::STATUS_COMPATIBLE_UPDATE => 'compatible-update',
);
?>

<span title="Composer updates" class="nette-composerUpdatesTab">
	<span class="<?php echo $classes[$status] ?>"></span>
	<?php if (!$updates) { ?>
	no update
	<?php } else { ?>
	<?php echo $updates . ' ' . ($updates === 1 ? 'update' : 'updates') ?>
	<?php } ?>
</span>
